# Generated by Django 5.2.17
# ruff: noqa: RUF012

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('identity', '0002_household_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='rewards',
                        to='identity.household',
                    ),
                ),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [
                    models.Index(
                        fields=['household', 'is_active', 'name'],
                        name='reward_hh_active_name_idx',
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower('name'),
                        models.F('household'),
                        name='reward_hh_name_ci_unique',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('points__gte', 1)),
                        name='reward_points_positive',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('name', ''), _negated=True),
                        name='reward_name_not_blank',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('reward_name', models.CharField(max_length=100)),
                ('reward_points', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('fulfilled', 'Fulfilled'),
                            ('cancelled', 'Cancelled'),
                        ],
                        default='pending',
                        max_length=9,
                    ),
                ),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                (
                    'child',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='redemptions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'decided_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='decided_redemptions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='redemptions',
                        to='identity.household',
                    ),
                ),
                (
                    'reward',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='redemptions',
                        to='rewards.reward',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [
                    models.Index(
                        fields=['household', 'status', '-created_at'],
                        name='redemption_hh_status_idx',
                    ),
                    models.Index(
                        fields=['child', 'status', '-created_at'],
                        name='redemption_child_status_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('child', 'idempotency_key'),
                        name='redemption_child_idempotency_key_unique',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                'status__in',
                                ('pending', 'fulfilled', 'cancelled'),
                            )
                        ),
                        name='redemption_status_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('decided_at__isnull', True), ('status', 'pending')
                            ),
                            models.Q(
                                models.Q(('status', 'pending'), _negated=True),
                                ('decided_at__isnull', False),
                            ),
                            _connector='OR',
                        ),
                        name='redemption_decision_matches_status',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('decided_by__isnull', True), ('status', 'pending')
                            ),
                            models.Q(('status', 'pending'), _negated=True),
                            _connector='OR',
                        ),
                        name='redemption_decided_by_unset_while_pending',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('reward_points__gte', 1)),
                        name='redemption_reward_points_positive',
                    ),
                ],
            },
        ),
    ]
