# Generated by Django 5.2.17 on 2026-09-09 00:10
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('identity', '0002_household_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAcknowledgement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('highest_level_shown', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='level_acknowledgements',
                        to='identity.household',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='level_acknowledgements',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('household', 'user'),
                        name='progression_levelacknowledgement_household_user_unique',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('highest_level_shown__gte', 0),
                            ('highest_level_shown__lte', 10),
                        ),
                        name='progression_levelacknowledgement_shown_level_range',
                    ),
                ],
            },
        ),
    ]
