# Generated by Django 5.2.17 on 2026-09-08 20:38
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('chores', '0001_initial'),
        ('identity', '0002_household_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('chore_name', models.CharField(max_length=100)),
                ('chore_points', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                            ('withdrawn', 'Withdrawn'),
                        ],
                        default='pending',
                        max_length=9,
                    ),
                ),
                ('idempotency_key', models.CharField(max_length=255)),
                (
                    'rejection_reason',
                    models.CharField(blank=True, default='', max_length=200),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                (
                    'child',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='submissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'chore',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='submissions',
                        to='chores.chore',
                    ),
                ),
                (
                    'decided_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='decided_submissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='submissions',
                        to='identity.household',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [
                    models.Index(
                        fields=['household', 'status', '-created_at'],
                        name='submission_hh_status_idx',
                    ),
                    models.Index(
                        fields=['child', 'status', '-created_at'],
                        name='submission_child_status_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('child', 'idempotency_key'),
                        name='submission_child_idempotency_key_unique',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('status', 'pending')),
                        fields=('child', 'chore'),
                        name='submission_one_pending_per_child_chore',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                'status__in',
                                ('pending', 'approved', 'rejected', 'withdrawn'),
                            )
                        ),
                        name='submission_status_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('decided_at__isnull', True), ('status', 'pending')
                            ),
                            models.Q(
                                models.Q(('status', 'pending'), _negated=True),
                                ('decided_at__isnull', False),
                            ),
                            _connector='OR',
                        ),
                        name='submission_decision_matches_status',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('decided_by__isnull', True), ('status', 'pending')
                            ),
                            models.Q(('status', 'pending'), _negated=True),
                            _connector='OR',
                        ),
                        name='submission_decided_by_unset_while_pending',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('chore_points__gte', 1)),
                        name='submission_chore_points_positive',
                    ),
                ],
            },
        ),
    ]
