# Generated by Django 5.2.17 on 2026-09-08 23:23
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='note',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
