# Generated by Django 5.2.17 on 2026-09-09 00:39
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('identity', '0003_parentpin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureSelection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('line_slug', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='creature_selections',
                        to='identity.household',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='creature_selections',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('household', 'user'),
                        name='creatures_creatureselection_household_user_unique',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                'line_slug__in',
                                (
                                    'dragon',
                                    'golem',
                                    'griffin',
                                    'phoenix',
                                    'kraken',
                                    'treant',
                                    'sphinx',
                                ),
                            )
                        ),
                        name='creatures_creatureselection_line_slug_known',
                    ),
                ],
            },
        ),
    ]
