"""
Django settings for the Chorum-murohc project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Runtime configuration


def _invalid(variable):
    raise ImproperlyConfigured(f'{variable} is invalid.')


def _required(variable):
    raise ImproperlyConfigured(f'{variable} is required.')


environment_value = os.environ.get('DJANGO_ENVIRONMENT')
if environment_value is None:
    DJANGO_ENVIRONMENT = 'development'
else:
    DJANGO_ENVIRONMENT = environment_value.strip().casefold()
    if DJANGO_ENVIRONMENT not in {'development', 'production'}:
        _invalid('DJANGO_ENVIRONMENT')

is_production = DJANGO_ENVIRONMENT == 'production'

secret_key_value = os.environ.get('DJANGO_SECRET_KEY')
if secret_key_value is None:
    if is_production:
        _required('DJANGO_SECRET_KEY')
    SECRET_KEY = 'django-insecure-local-development-only'
elif not secret_key_value.strip():
    _invalid('DJANGO_SECRET_KEY')
else:
    SECRET_KEY = secret_key_value

debug_value = os.environ.get('DJANGO_DEBUG')
if debug_value is None:
    DEBUG = not is_production
else:
    normalised_debug = debug_value.strip().casefold()
    if normalised_debug in {'1', 'true', 'yes', 'on'}:
        DEBUG = True
    elif normalised_debug in {'0', 'false', 'no', 'off'}:
        DEBUG = False
    else:
        _invalid('DJANGO_DEBUG')

if is_production and DEBUG:
    _invalid('DJANGO_DEBUG')

allowed_hosts_value = os.environ.get('DJANGO_ALLOWED_HOSTS')
if allowed_hosts_value is None:
    if is_production:
        _required('DJANGO_ALLOWED_HOSTS')
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']
else:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_value.split(',')]
    if not ALLOWED_HOSTS or any(not host or host == '*' for host in ALLOWED_HOSTS):
        _invalid('DJANGO_ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chorum_murohc.apps.ChorumMurohcConfig',
    'chorum_murohc.identity.apps.IdentityConfig',
    'chorum_murohc.audit.apps.AuditConfig',
    'chorum_murohc.chores.apps.ChoresConfig',
    'chorum_murohc.submissions.apps.SubmissionsConfig',
    'chorum_murohc.ledger.apps.LedgerConfig',
    'chorum_murohc.rewards.apps.RewardsConfig',
    'chorum_murohc.progression.apps.ProgressionConfig',
    'chorum_murohc.creatures.apps.CreaturesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_engine_value = os.environ.get('DJANGO_DB_ENGINE')
if database_engine_value is None:
    if is_production:
        _required('DJANGO_DB_ENGINE')
    database_engine = 'sqlite'
else:
    database_engine = database_engine_value.strip().casefold()
    if database_engine not in {'sqlite', 'postgresql'}:
        _invalid('DJANGO_DB_ENGINE')

if is_production and database_engine != 'postgresql':
    _invalid('DJANGO_DB_ENGINE')

if database_engine == 'sqlite':
    for conflicting_variable in (
        'DJANGO_DB_USER',
        'DJANGO_DB_PASSWORD',
        'DJANGO_DB_HOST',
        'DJANGO_DB_PORT',
    ):
        if conflicting_variable in os.environ:
            raise ImproperlyConfigured(
                f'{conflicting_variable} conflicts with DJANGO_DB_ENGINE.'
            )

    database_name_value = os.environ.get('DJANGO_DB_NAME')
    if database_name_value is None:
        database_name = BASE_DIR / 'db.sqlite3'
    elif not database_name_value.strip():
        _invalid('DJANGO_DB_NAME')
    elif database_name_value == ':memory:':
        database_name = database_name_value
    else:
        database_name_path = Path(database_name_value)
        database_name = (
            database_name_path
            if database_name_path.is_absolute()
            else BASE_DIR / database_name_path
        )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': database_name,
        }
    }
else:
    database_variables = (
        'DJANGO_DB_NAME',
        'DJANGO_DB_USER',
        'DJANGO_DB_PASSWORD',
        'DJANGO_DB_HOST',
        'DJANGO_DB_PORT',
    )
    database_values = {}
    for database_variable in database_variables:
        database_value = os.environ.get(database_variable)
        if database_value is None or not database_value.strip():
            _required(database_variable)
        database_values[database_variable] = database_value

    database_port_value = database_values['DJANGO_DB_PORT']
    if not database_port_value.isascii() or not database_port_value.isdecimal():
        _invalid('DJANGO_DB_PORT')
    database_port = int(database_port_value, 10)
    if not 1 <= database_port <= 65535:
        _invalid('DJANGO_DB_PORT')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': database_values['DJANGO_DB_NAME'],
            'USER': database_values['DJANGO_DB_USER'],
            'PASSWORD': database_values['DJANGO_DB_PASSWORD'],
            'HOST': database_values['DJANGO_DB_HOST'],
            'PORT': str(database_port),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
