"""
Django settings for the Chorum-murohc project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Runtime configuration


def _invalid(variable):
    raise ImproperlyConfigured(f'{variable} is invalid.')


def _required(variable):
    raise ImproperlyConfigured(f'{variable} is required.')


def _read_boolean(variable, default):
    value = os.environ.get(variable)
    if value is None:
        return default
    normalised = value.strip().casefold()
    if normalised in {'1', 'true', 'yes', 'on'}:
        return True
    if normalised in {'0', 'false', 'no', 'off'}:
        return False
    # Always raises; there is no fourth outcome.
    _invalid(variable)


environment_value = os.environ.get('DJANGO_ENVIRONMENT')
if environment_value is None:
    DJANGO_ENVIRONMENT = 'development'
else:
    DJANGO_ENVIRONMENT = environment_value.strip().casefold()
    if DJANGO_ENVIRONMENT not in {'development', 'production'}:
        _invalid('DJANGO_ENVIRONMENT')

is_production = DJANGO_ENVIRONMENT == 'production'

# The key itself, or a file holding it. The variable wins when both are
# given. The file is how the container does it: the entrypoint generates one
# into the state volume on the first start, and reading it from settings -
# rather than exporting it from the entrypoint - means every process in the
# container has it, including `docker compose exec ... manage.py`.
secret_key_value = os.environ.get('DJANGO_SECRET_KEY')
secret_key_file_value = os.environ.get('DJANGO_SECRET_KEY_FILE')
if secret_key_value is not None:
    if not secret_key_value.strip():
        _invalid('DJANGO_SECRET_KEY')
    SECRET_KEY = secret_key_value
elif secret_key_file_value is not None:
    try:
        secret_key_file_contents = Path(secret_key_file_value).read_text()
    except OSError:
        _invalid('DJANGO_SECRET_KEY_FILE')
    SECRET_KEY = secret_key_file_contents.strip()
    if not SECRET_KEY:
        _invalid('DJANGO_SECRET_KEY_FILE')
elif is_production:
    _required('DJANGO_SECRET_KEY')
else:
    SECRET_KEY = 'django-insecure-local-development-only'

DEBUG = _read_boolean('DJANGO_DEBUG', not is_production)

if is_production and DEBUG:
    _invalid('DJANGO_DEBUG')

# Whether browsers reach this deployment over HTTPS. One switch for every
# transport-dependent setting below: Secure cookies, the redirect to HTTPS,
# and HSTS. It follows the environment unless it is set, so a production
# deployment is hardened by default.
#
# A household running the container on its own network over plain HTTP has to
# set DJANGO_HTTPS=false. A Secure cookie is never sent over HTTP, so leaving
# this true there would mean nobody could sign in. That choice is a real
# downgrade, not a formality: `manage.py check --deploy` then reports the
# four transport warnings it earns, and `README.md` says so.
USE_HTTPS = _read_boolean('DJANGO_HTTPS', is_production)

allowed_hosts_value = os.environ.get('DJANGO_ALLOWED_HOSTS')
if allowed_hosts_value is None:
    if is_production:
        _required('DJANGO_ALLOWED_HOSTS')
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']
else:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_value.split(',')]
    if not ALLOWED_HOSTS or any(not host or host == '*' for host in ALLOWED_HOSTS):
        _invalid('DJANGO_ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'chorum_murohc.apps.ChorumMurohcConfig',
    'chorum_murohc.identity.apps.IdentityConfig',
    'chorum_murohc.audit.apps.AuditConfig',
    'chorum_murohc.chores.apps.ChoresConfig',
    'chorum_murohc.submissions.apps.SubmissionsConfig',
    'chorum_murohc.ledger.apps.LedgerConfig',
    'chorum_murohc.rewards.apps.RewardsConfig',
    'chorum_murohc.progression.apps.ProgressionConfig',
    'chorum_murohc.creatures.apps.CreaturesConfig',
    'chorum_murohc.interest.apps.InterestConfig',
]

AUTH_USER_MODEL = 'identity.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.content_security_policy',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_engine_value = os.environ.get('DJANGO_DB_ENGINE')
if database_engine_value is None:
    if is_production:
        _required('DJANGO_DB_ENGINE')
    database_engine = 'sqlite'
else:
    database_engine = database_engine_value.strip().casefold()
    if database_engine not in {'sqlite', 'postgresql'}:
        _invalid('DJANGO_DB_ENGINE')

if is_production and database_engine != 'postgresql':
    _invalid('DJANGO_DB_ENGINE')

if database_engine == 'sqlite':
    if 'DJANGO_DB_TARGET' in os.environ:
        _invalid('DJANGO_DB_TARGET')

    for conflicting_variable in (
        'DJANGO_DB_USER',
        'DJANGO_DB_PASSWORD',
        'DJANGO_DB_HOST',
        'DJANGO_DB_PORT',
    ):
        if conflicting_variable in os.environ:
            raise ImproperlyConfigured(
                f'{conflicting_variable} conflicts with DJANGO_DB_ENGINE.'
            )

    database_name_value = os.environ.get('DJANGO_DB_NAME')
    if database_name_value is None:
        database_name = BASE_DIR / 'db.sqlite3'
    elif not database_name_value.strip():
        _invalid('DJANGO_DB_NAME')
    elif database_name_value == ':memory:':
        database_name = database_name_value
    else:
        database_name_path = Path(database_name_value)
        if database_name_path.is_absolute():
            database_name = database_name_path
        else:
            database_name = (BASE_DIR / database_name_path).resolve()
            if not database_name.is_relative_to(BASE_DIR):
                _invalid('DJANGO_DB_NAME')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': database_name,
        }
    }
else:
    database_target_value = os.environ.get('DJANGO_DB_TARGET')
    if is_production:
        if database_target_value is not None:
            _invalid('DJANGO_DB_TARGET')
        database_target = None
    else:
        if database_target_value is None:
            _required('DJANGO_DB_TARGET')
        if not (
            re.fullmatch(r'task_t[0-9]{3}_[a-z0-9]{8,16}', database_target_value)
            or re.fullmatch(
                r'ci_[0-9]{1,20}_[0-9]{1,3}_[a-z0-9]{8,16}',
                database_target_value,
            )
        ):
            _invalid('DJANGO_DB_TARGET')
        database_target = database_target_value

    database_variables = (
        'DJANGO_DB_NAME',
        'DJANGO_DB_USER',
        'DJANGO_DB_PASSWORD',
        'DJANGO_DB_HOST',
        'DJANGO_DB_PORT',
    )
    database_values = {}
    for database_variable in database_variables:
        database_value = os.environ.get(database_variable)
        if database_value is None or not database_value.strip():
            _required(database_variable)
        database_values[database_variable] = database_value

    database_port_value = database_values['DJANGO_DB_PORT']
    if not database_port_value.isascii() or not database_port_value.isdecimal():
        _invalid('DJANGO_DB_PORT')
    database_port = database_port_value.lstrip('0') or '0'
    if (
        database_port == '0'
        or len(database_port) > 5
        or (len(database_port) == 5 and database_port > '65535')
    ):
        _invalid('DJANGO_DB_PORT')

    database_configuration = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': database_values['DJANGO_DB_NAME'],
        'USER': database_values['DJANGO_DB_USER'],
        'PASSWORD': database_values['DJANGO_DB_PASSWORD'],
        'HOST': database_values['DJANGO_DB_HOST'],
        'PORT': database_port,
    }

    if database_target is not None:
        expected_database_name = f'chorum_murohc_{database_target}'
        if database_values['DJANGO_DB_NAME'] != expected_database_name:
            _invalid('DJANGO_DB_NAME')
        if database_values['DJANGO_DB_USER'] != expected_database_name:
            _invalid('DJANGO_DB_USER')

        expected_host = (
            '127.0.0.1' if database_target.startswith('task_') else 'postgres'
        )
        if database_values['DJANGO_DB_HOST'] != expected_host:
            _invalid('DJANGO_DB_HOST')

        database_configuration['TEST'] = {
            'NAME': f'test_{expected_database_name}',
        }

    DATABASES = {'default': database_configuration}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Sessions and CSRF
# https://docs.djangoproject.com/en/5.2/topics/http/sessions/
#
# Same-origin Django sessions are the only authentication mechanism, as
# required by the `Session and CSRF Policy` section of `_docs/design.md`.
# There is no JWT, bearer token, or browser-stored authentication token.

# Fourteen days, with no idle timeout and no extension on activity.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Script must never read the session cookie. The interface does have to read
# the CSRF cookie to echo its value back, so only the session cookie is
# HttpOnly, and both cookies stay same-site.
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# A Secure cookie is only ever sent over HTTPS, so both cookies follow the
# transport rather than the environment: marking them Secure on a deployment
# reached over plain HTTP would stop them being sent at all.
SESSION_COOKIE_SECURE = USE_HTTPS
CSRF_COOKIE_SECURE = USE_HTTPS


# Transport hardening (S-02), all of it following `DJANGO_HTTPS` rather than
# the environment. Development serves plain HTTP, and so does a household
# container on its own network, and every rule here is actively harmful
# there: the redirect would loop and HSTS would tell the browser to refuse
# the plain-HTTP address it was just served on. A year, and including
# subdomains, is the standard HSTS starting point.
SECURE_SSL_REDIRECT = USE_HTTPS
SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365 if USE_HTTPS else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = USE_HTTPS

# HTTPS is terminated by whatever proxy the operator puts in front, so Django
# has to be told which request reached it over TLS or the redirect above
# never settles. This trusts `X-Forwarded-Proto`, which is only safe because
# it is set exclusively when the operator says a proxy is there; nothing
# outside that proxy may reach the container.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if USE_HTTPS else None

# Nothing in this product is ever framed, by itself or by anyone else.
X_FRAME_OPTIONS = 'DENY'

# `check --deploy` also warns W021 unless `SECURE_HSTS_PRELOAD` is True, but
# that setting exists to signal actual submission to the browser vendors'
# hardcoded preload list - a near-irreversible step (removal takes months
# and every browser release) for a household app that may not even sit on a
# stable public domain. Silenced deliberately rather than set for a
# consequence this project has not decided to take on.
SILENCED_SYSTEM_CHECKS = ['security.W021']


# Caches
# https://docs.djangoproject.com/en/5.2/topics/cache/
#
# The login throttle keeps its counters in a cache of its own, so clearing an
# application cache can never reset the abuse control. It is database-backed
# rather than local memory so that every application process shares one set
# of counters instead of each counting its own (issue 128); PostgreSQL is
# already the one dependency this needs. The table is created by the
# `chorum_murohc` migration `0001_login_throttle_cache_table`, so it exists
# before anything tries to use it.

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'login_throttle': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'login_throttle_cache',
    },
}


# Django REST Framework

REST_FRAMEWORK = {
    # Wraps DRF's own exception handler to log every refused authentication,
    # CSRF and permission event (S-04); see
    # `chorum_murohc.api.security_logging`. The response every endpoint
    # returns is unchanged.
    'EXCEPTION_HANDLER': (
        'chorum_murohc.api.security_logging.logging_exception_handler'
    ),
    # Login is the only throttled endpoint, so no default throttle class is
    # registered here. Both scopes are keyed on the client address and never
    # on the submitted username: keying on a name would let an attacker lock
    # out a named account and would leak which accounts exist.
    'DEFAULT_THROTTLE_RATES': {
        'login_burst': '10/minute',
        'login_sustained': '100/hour',
    },
    # Trust no forwarding header: the client address is the peer address
    # alone, so a forged `X-Forwarded-For` cannot buy a fresh allowance.
    # Raise this only for a known, counted reverse proxy in front of Django.
    'NUM_PROXIES': 0,
}


# Logging (S-04)
# https://docs.djangoproject.com/en/5.2/topics/logging/
#
# One logger, one handler, always on: not gated by DEBUG the way Django's own
# default console handler is, since a refusal in production is exactly what
# this exists to show. `chorum_murohc.api.security_logging` is the only
# writer; it logs a method, a path and a status code, never a secret or any
# household content. `propagate=False` keeps every line out of Django's own
# `django` logger, so it is never duplicated into `mail_admins` or anywhere
# else a later change to the root logging config might send it.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'security': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'security_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'security',
        },
    },
    'loggers': {
        'chorum_murohc.security': {
            'handlers': ['security_console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# `collectstatic` writes here at image build time, and `config.spa` serves
# this directory at STATIC_URL. Only the admin's own files land here; the
# household interface is the Vite build below.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The built interface, served from the same origin as the API by
# `config.spa`. `pnpm --dir frontend build` writes it.
FRONTEND_DIST = BASE_DIR / 'frontend' / 'dist'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
