# Generated by Django 5.2.17 on 2026-09-08 17:14
# ruff: noqa: RUF012

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('identity', '0002_household_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='chores',
                        to='identity.household',
                    ),
                ),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [
                    models.Index(
                        fields=['household', 'is_active', 'name'],
                        name='chore_hh_active_name_idx',
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower('name'),
                        models.F('household'),
                        name='chore_hh_name_ci_unique',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('points__gte', 1)),
                        name='chore_points_positive',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('name', ''), _negated=True),
                        name='chore_name_not_blank',
                    ),
                ],
            },
        ),
    ]
