# Generated by Django 5.2.17 on 2026-09-06 15:49
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[('parent', 'Parent'), ('child', 'Child')], max_length=6
                    ),
                ),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memberships',
                        to='identity.household',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='household_memberships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(
                related_name='households',
                through='identity.Membership',
                through_fields=('household', 'user'),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(
                fields=('household', 'user'),
                name='identity_membership_household_user_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(
                condition=models.Q(('role__in', ('parent', 'child'))),
                name='identity_membership_role_valid',
            ),
        ),
    ]
