# Generated by Django 5.2.17
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identity', '0002_household_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentPin',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('pin_hash', models.CharField(max_length=255)),
                ('failed_attempts', models.SmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parent_pin',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='parentpin',
            constraint=models.CheckConstraint(
                condition=models.Q(('failed_attempts__gte', 0)),
                name='identity_parentpin_failed_attempts_not_negative',
            ),
        ),
    ]
