# Generated by Django 5.2.17 on 2026-09-08 16:38
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('identity', '0002_household_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('amount', models.BigIntegerField()),
                (
                    'reason',
                    models.CharField(
                        choices=[
                            ('chore_credit', 'Chore credit'),
                            ('interest', 'Interest'),
                            ('reward_debit', 'Reward debit'),
                            ('level_debit', 'Level debit'),
                        ],
                        max_length=32,
                    ),
                ),
                ('source_type', models.CharField(max_length=100)),
                ('source_id', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ledger_entries',
                        to='identity.household',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ledger_entries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [
                    models.Index(
                        fields=['user', '-created_at', '-id'],
                        name='ledger_entry_user_time_idx',
                    ),
                    models.Index(
                        fields=['household', '-created_at', '-id'],
                        name='ledger_entry_hh_time_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'idempotency_key'),
                        name='ledger_entry_user_idempotency_key_unique',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('amount', 0), _negated=True),
                        name='ledger_entry_amount_not_zero',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                'reason__in',
                                (
                                    'chore_credit',
                                    'interest',
                                    'reward_debit',
                                    'level_debit',
                                ),
                            )
                        ),
                        name='ledger_entry_reason_valid',
                    ),
                ],
            },
        ),
    ]
